[package]
name = "wallcovedaemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wallcovedaemon"
path = "src/main.rs"

[dependencies]
wallcove-core.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow = "1.0.102"